#+title: New Jack Swing
#+author: SciPunch

Make no mistake, this genre has nothing to do with Swing. On the contrary, New Jack Swing (NJS) is the updated continuation of the Philadelphia Sound: the body of Philly Soul in a brand new jacket of Rap. Strong, funky breakbeats no longer form the rhythm for messages of protest or gangster lyrics, but for smooth, harmonic vocals talking about love and romance. Although many (male) New Jack Swing artists seemed like young, innocent casanovas, they often had hidden gangster habits, preluding an era of East Coast Gangsta Rap. Swingbeat (a synonym for NJS) is exactly the way it sounds: extremely catchy and funky with strong emphasis on beat.

The TV-series “The Fresh Prince of Bel-Air” starring Will Smith knew how to bring New Jack Swing to a larger audience, featuring some of its songs alongside that particular late eighties New Jack Swing fashion: loose Hip-Hop wear with flashy colors, round sunglasses, female dreads or male hightop haircuts. But what makes this genre of particular gravity is the marriage of Rhythm ‘n Blues and Rap into Urban, a strong bond that has never fallen apart since.

New Jack Swing evolves into Urban Soul, but sometimes overlaps with it as well. New Jack Swing was already known as Contemporary Soul or Urban Soul before the rise of the latter, after all. 
