#+title: UK Garage
#+author: SciPunch

Drum ‘n’ Bass was hip because it was underground and brand new. The problem was that it sounded too heavy and hardcore for the masses (Hardstep, Techstep, Darkcore…) and that it detracted too many women from going to the clubs. British upper class designers and fashionistas created their own hipster version of Drum ‘n’ Bass, particularly aimed at increasing female club presence. By merging Garage House with Old Skool Jungle and adding sampled (Neo-Soul) vocals, a smooth, textured music was being created that had little in common with regular Drum ‘n’ Bass. Fine, hi-pitched breakbeats and delicate snares made this music unlike anything one would expect at a garage, although it was named UK Garage. This was fancy Breakbeat. Fast, but gentle, bass-driven but with a subtle timbre.

The first form of UK Garage was a rapid type of syncopated Garage House, known as Speed Garage. Speed Garage’s abundant percussion and heavy bass made the influences from Garage House barely noticeable and thus was still not good enough to attract a large female crowd. The genre did however attract immediate attention from major record labels. Speed Garage became influenced by Ragga and Drum ‘n’ Bass (particularly Hardstep) which altered its time signature in two beats per bar instead of four, which is known as “2-Step”. Despite these influences, 2-Step Garage abandoned bass in favor of sharp but soft treble and returned the sound of Garage House with a touch of R&B.

These two UK Garage genres marked the start of a large music family - also known as UK Garage - that led to Dubstep and UK Bass. But 2-Step is also the beginning of Nu R&B. Not only due to its sound and rhythm, but by spreading a culture of upper-class clubbing that became notorious (and eventually despised) for its cocain use and promiscuous encounters.
